# netlify.toml (root)

[build]
  command   = "npm ci && npm run build:web && cp public/sw.js dist/sw.js"
  publish   = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# ✅ schedule a function named "send-daily"
[functions."send-daily"]
  schedule = "0 15 * * *"   # daily 15:00 UTC

# SPA routing for Expo export
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# SW headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Service-Worker-Allowed = "/"
    Cache-Control = "no-cache"
